version: '3'

services:
  php:
    image: php:7.4-rc-fpm
    container_name: php
    volumes:
    - ../webapps:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ../webapps:/var/www
    - ./nginx:/etc/nginx/conf.d
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ../mysql57/db/data:/var/lib/mysql
    - ../mysql57/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ../mysql57/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

